# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Admin-Config
version:      0.94
version_from: lib/Apache/Admin/Config.pm
installdirs:  site
requires:
    FileHandle:                    2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
